version: '3'
services:
  web:
    build: .
    image: final_quiz_spring_boot_app:v1.0
    container_name: final_quiz_spring_boot_app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      FINAL_QUIZ_MYSQL_URL: jdbc:mysql://mysql:3306/final_quiz?characterEncoding=utf8&characterSetResults=utf8
      FINAL_QUIZ_MYSQL_ROOT_USERNAME: root
      FINAL_QUIZ_MYSQL_ROOT_PASSWORD: password