kind: Service
apiVersion: v1
metadata:
  name: final-quiz-spring-boot-app-service
  namespace: final-quiz
spec:
  type: NodePort
  selector:
    app: final-quiz-spring-boot-app
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-quiz-spring-boot-app-deployment
  namespace: final-quiz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: final-quiz-spring-boot-app
  template:
    metadata:
      labels:
        app: final-quiz-spring-boot-app
    spec:
      containers:
        - name: final-quiz-spring-boot-app
          image: imdreamer/final_quiz_spring_boot_app
          ports:
            - containerPort: 8080
          env:
            - name: FINAL_QUIZ_MYSQL_URL
              value: jdbc:mysql://mysql:3306/final_quiz?characterEncoding=utf8&characterSetResults=utf8
            - name: FINAL_QUIZ_MYSQL_ROOT_USERNAME
              value: root
            - name: FINAL_QUIZ_MYSQL_ROOT_PASSWORD
              value: password