spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: ${FINAL_QUIZ_MYSQL_URl:jdbc:mysql://127.0.0.1:3306/final_quiz?characterEncoding=utf8&characterSetResults=utf8}
    username: ${FINAL_QUIZ_MYSQL_ROOT_USERNAME:root}
    password: ${FINAL_QUIZ_MYSQL_ROOT_PASSWORD:password}
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE